### ISSUE TITLE
kessonsuu関数

### ISSUE THREAD

**Issue by takaemonn** [RyuhoFukuda/ProjExD#1]
https://github.com/RyuhoFukuda/ProjExD/blob/809686352ccd621932ef26d5d50cdbfd5b73d1fb/ex01/alphabet.py#L34
kaito関数とは別に処理しているのが面白い

**Comment by RyuhoFukuda** [comment]
欠損数がいくつかを判別する関数なのでkessonsuu関数についてはあってると思いますがセンスがないので修正します。ありがとうございました。kaito関数とは別でやったほうが簡単に修正できると思いそうしました。

**Comment by RyuhoFukuda** [comment]
kessonsuu関数の関数の名前をdis_alに変更しました。
