### ISSUE TITLE
画像がない

### ISSUE THREAD

**Issue by suzukiyukito** [RyuhoFukuda/ProjExD#13]
実際にプレイしてみたところ、どこにもこの画像がないです
https://github.com/RyuhoFukuda/ProjExD/blob/a87da98d21c898e6baf4400dde00069522469a68/ex06/hopping.py#L155

**Comment by RyuhoFukuda** [comment]
画像も一緒にex06フォルダにpush致しました。ご一緒にダウンロードしてお楽しみください。
