### ISSUE TITLE
さらにコードを短くできそう

### ISSUE THREAD

**Issue by c0b21033** [RyuhoFukuda/ProjExD#3]
https://github.com/RyuhoFukuda/ProjExD/blob/85a888bd956136d92031d76f025f396476349ac4/ex02/calc.py#L54　表示するtext=""の中身をi==-1の時は+、i==-2の時は-、というのを別の変数に入れておき、ボタンの位置は固定にすることで、その後のbuttonの三行の繰り返しを避けることができコードが短く、見やすくなると思いました。

**Comment by RyuhoFukuda** [comment]
指摘された箇所を修正しようとしましたが、固定にしないことでrowとcolumnの変数の初期値を変更するだけで電卓のボタンが一括で移動するようにしているため、gridの数値を固定にしていないので、関数にする場所を限定したところ、関数内に入る変数と関数外の変数で齟齬が生じたため、関数にまとめることができなかった。おそらく、gridに使う変数を固定にしてリストとしてまとめておき、今回指摘された+等の符号と、gridに使う変数を固定にしたリストを引数として受け取る関数を作れば関数内外の変数（button）が一致するのでできる可能性があると考えられます。ですが、今回では時間内で終わらないことと今後の拡張性を考えて電卓のボタンを一括で移動することができることのほうが有用だと考えたため、コードを短くするためにgridに使う変数を固定して関数を作ることはできないと判断して、できませんでした。
