### ISSUE TITLE
改行

### ISSUE THREAD

**Issue by c0b21027** [RyuhoFukuda/ProjExD#5]
書くこと何もありませんでした。
他の行が改行せずにreturnされているのでここも改行せずに書いてみてはどうですか？https://github.com/RyuhoFukuda/ProjExD/blob/b2a75f460f336d069a5113f4d9e4bb188b5e90bf/ex04/dodge_bomb.py#L76

**Comment by RyuhoFukuda** [comment]
コメントをいただく前に解消してgitにpushしていました。申し訳ございませんでした。
