### ISSUE TITLE
コンフリクトエラーの解消

### ISSUE THREAD

**Issue by takaemonn** [RyuhoFukuda/ProjExD#6]
https://github.com/RyuhoFukuda/ProjExD/blob/b2a75f460f336d069a5113f4d9e4bb188b5e90bf/ex04/dodge_bomb.py#L1
gitにaddしたときにコンフリクトエラーを解消していないので、mainとbrunchのコードが混ざった状態になっています。どこがコードとして使われているのがわかりにくいです。

**Comment by RyuhoFukuda** [comment]
コメントをいただく前に解消してgitにpushしていました。申し訳ございませんでした。
